### ISSUE TITLE
Problem with DocumentType

### ISSUE THREAD

**Issue by emt1o** [MakeITBologna/zefiro#3]
Salve,
ho installato Zefiro in locale e dopo averlo configurato e fatto il login mi restituisce una pagina di errore :
![cattura](https://cloud.githubusercontent.com/assets/7427799/18126824/53bf75e8-6f7d-11e6-8d8a-010359ebb051.PNG)

allego anche i file di log

[zefiro.txt](https://github.com/MakeITBologna/zefiro/files/447034/zefiro.txt)
[zefiro.errors.txt](https://github.com/MakeITBologna/zefiro/files/447035/zefiro.errors.txt)

**Comment by andreafeccomandi** [comment]
Salve,
l'errore è dovuto al fatto che Zefiro gestisce i tipi documento discendenti dal tipo base specificato nel parametro alfresco/@baseTypeId  in WEB-inf/classes/jbrickConfig.xml.

Nell'installazione di Alfresco legata a Zefiro molto probabilmente non ci sono tipi documento discendenti del tipo documento base.

**Comment by emt1o** [comment]
Salve,
nel file di conf WEB-inf/classes/jbrickConfig.xml ho aggiunto prima questo 
`<alfresco baseTypeId="cm:dictionaryModel:gafp:FatturaPassivaINGRESSO" host="http://127.0.0.1:8080" rootFolderId="768e1e50-0a67-4553-b987-eacfdd3deee5"/>`
con il medesimo risultato e poi ho provato così
`<alfresco baseTypeId="cm:dictionaryModel" host="http://127.0.0.1:8080" rootFolderId="768e1e50-0a67-4553-b987-eacfdd3deee5"/>`
ma non cambia nulla, sempre lo stesso errore mi restituisce.
![cattura](https://cloud.githubusercontent.com/assets/7427799/18163285/7ea68892-703a-11e6-8130-73a9d441538a.PNG)
Grazie per l'aiuto e a presto.

**Comment by andreafeccomandi** [comment]
Salve,

sulla base della screenshot inviato, il file di conf `WEB-inf/classes/jbrickConfig.xml` deve essere valorizzato così:

`<alfresco baseTypeId="gafp:FatturaPassivaINGRESSO" host="http://127.0.0.1:8080" rootFolderId="768e1e50-0a67-4553-b987-eacfdd3deee5"/>`

**Comment by meden** [comment]
@emt1o, ha risolto il suo problema? È possibile chiudere questa issue?

**Comment by Arzerilla** [comment]
@emt1o , chiudo la issue poichè è passato molto tempo. In caso di necessità può riaprire una nuova issue.
